// Curated list of well-known actors used to seed the "Actor you most see
// yourself in" pick question. /person/popular thins out on actors deeper
// into the list (more musicians, athletes, presenters), which left later
// filtered pages sparse. We hydrate this list at runtime via /search/person
// (cached by Next.js) so names/photos/popularity stay fresh.
//
// Order here is not meaningful — results are sorted by TMDB popularity once
// hydrated. Add names as needed; duplicates and unknowns are dropped quietly.
export const POPULAR_ACTOR_NAMES: readonly string[] = [
  // Marquee leading men
  "Leonardo DiCaprio",
  "Tom Hanks",
  "Tom Cruise",
  "Brad Pitt",
  "Denzel Washington",
  "Robert De Niro",
  "Al Pacino",
  "Christian Bale",
  "Joaquin Phoenix",
  "Matt Damon",
  "Ben Affleck",
  "Will Smith",
  "Robert Downey Jr.",
  "Chris Evans",
  "Chris Hemsworth",
  "Chris Pratt",
  "Mark Ruffalo",
  "Jeremy Renner",
  "Ryan Gosling",
  "Ryan Reynolds",
  "Hugh Jackman",
  "Keanu Reeves",
  "Harrison Ford",
  "Daniel Craig",
  "Idris Elba",
  "Mahershala Ali",
  "Adrien Brody",
  "Mads Mikkelsen",
  "Cillian Murphy",
  "Tom Hardy",
  "Michael Fassbender",
  "Jake Gyllenhaal",
  "Andrew Garfield",
  "Tobey Maguire",
  "Timothée Chalamet",
  "Paul Mescal",
  "Austin Butler",
  "Pedro Pascal",
  "Oscar Isaac",
  "John Boyega",
  "Daniel Kaluuya",
  "Lakeith Stanfield",
  "Samuel L. Jackson",
  "Morgan Freeman",
  "Anthony Hopkins",
  "Daniel Day-Lewis",
  "Gary Oldman",
  "Ralph Fiennes",
  "Colin Farrell",
  "Brendan Gleeson",
  "Jeff Bridges",
  "Bryan Cranston",
  "Jeffrey Wright",
  "Steve Carell",
  "Will Ferrell",
  "Bill Murray",
  "Jim Carrey",
  "Eddie Murphy",
  "Adam Sandler",
  "Jonah Hill",
  "Seth Rogen",
  "Paul Rudd",
  "Jason Bateman",
  // Marquee leading women
  "Meryl Streep",
  "Cate Blanchett",
  "Nicole Kidman",
  "Charlize Theron",
  "Julianne Moore",
  "Frances McDormand",
  "Viola Davis",
  "Kate Winslet",
  "Tilda Swinton",
  "Helena Bonham Carter",
  "Jennifer Lawrence",
  "Emma Stone",
  "Margot Robbie",
  "Anne Hathaway",
  "Natalie Portman",
  "Scarlett Johansson",
  "Penélope Cruz",
  "Saoirse Ronan",
  "Florence Pugh",
  "Zendaya",
  "Anya Taylor-Joy",
  "Jessica Chastain",
  "Amy Adams",
  "Rachel McAdams",
  "Emily Blunt",
  "Rooney Mara",
  "Carey Mulligan",
  "Brie Larson",
  "Lupita Nyong'o",
  "Tessa Thompson",
  "Zoe Saldaña",
  "Gal Gadot",
  "Olivia Colman",
  "Sandra Bullock",
  "Reese Witherspoon",
  "Drew Barrymore",
  "Salma Hayek",
  "Eva Green",
  "Marion Cotillard",
  "Léa Seydoux",
  "Isabelle Huppert",
  "Juliette Binoche",
  "Toni Collette",
  "Octavia Spencer",
];
