// Curated list of well-known directors used to seed the "Auto-watch director"
// pick question. TMDB's /person/popular endpoint is overwhelmingly actors and
// surfaces only a handful of directors across hundreds of entries, which left
// the grid almost empty. Instead, we hydrate this list at runtime via
// /search/person (cached by Next.js) so names/photos/popularity stay fresh.
//
// Order here is not meaningful — results are sorted by TMDB popularity once
// hydrated. Add names as needed; duplicates and unknowns are dropped quietly.
export const POPULAR_DIRECTOR_NAMES: readonly string[] = [
  "Christopher Nolan",
  "Quentin Tarantino",
  "Steven Spielberg",
  "Martin Scorsese",
  "Denis Villeneuve",
  "Stanley Kubrick",
  "Wes Anderson",
  "David Fincher",
  "Ridley Scott",
  "James Cameron",
  "Greta Gerwig",
  "Jordan Peele",
  "Bong Joon-ho",
  "Hayao Miyazaki",
  "Alfred Hitchcock",
  "Francis Ford Coppola",
  "Paul Thomas Anderson",
  "David Lynch",
  "Tim Burton",
  "Guillermo del Toro",
  "Damien Chazelle",
  "Sofia Coppola",
  "Ari Aster",
  "Pedro Almodóvar",
  "Park Chan-wook",
  "Yorgos Lanthimos",
  "Robert Eggers",
  "Darren Aronofsky",
  "Edgar Wright",
  "Taika Waititi",
  "Charlie Kaufman",
  "Spike Jonze",
  "Joel Coen",
  "Ethan Coen",
  "Akira Kurosawa",
  "Sergio Leone",
  "Billy Wilder",
  "Roman Polanski",
  "Andrei Tarkovsky",
  "Federico Fellini",
  "Ingmar Bergman",
  "John Carpenter",
  "Brian De Palma",
  "Spike Lee",
  "Clint Eastwood",
  "Peter Jackson",
  "M. Night Shyamalan",
  "Sam Mendes",
  "Wong Kar-wai",
  "Nuri Bilge Ceylan",
  "Hirokazu Kore-eda",
  "Céline Sciamma",
  "Lynne Ramsay",
  "Jane Campion",
  "Kathryn Bigelow",
  "Chloé Zhao",
  "Barry Jenkins",
  "Rian Johnson",
  "Alfonso Cuarón",
  "Alejandro González Iñárritu",
  "Guillermo Arriaga",
  "Fatih Akın",
  "Asghar Farhadi",
  "Lars von Trier",
  "Michael Haneke",
  "Werner Herzog",
  "Terrence Malick",
  "Paul Verhoeven",
  "Luca Guadagnino",
  "Noah Baumbach",
  "Jim Jarmusch",
  "Sergei Parajanov",
];
